# Generated by Django 2.2.1 on 2020-02-10 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='example2',
            table='Example2',
        ),
    ]
